version: '3.8'

services:
  api:
    image: python:3.11-slim
    container_name: noname-api
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    command: |
      sh -c "pip install flask && python -c \"
      from flask import Flask, jsonify
      app = Flask(__name__)
      
      @app.route('/')
      def home():
          return jsonify({'message': 'Welcome No Name Security!'}), 200
      
      app.run(host='0.0.0.0', port=5000, debug=True)
      \""