version: '3.8'

services:
  api:
    image: python:3.11-slim
    container_name: noname-api
    restart: always
    working_dir: /app
    command: |
      sh -c "pip install flask && cat > app.py << 'EOF'
      from flask import Flask, request, jsonify
      
      app = Flask(__name__)
      
      @app.route('/')
      def home():
          response_name = {'message': 'Welcome No Name Security!'}
          return jsonify(response_name), 200
      
      if __name__ == '__main__':
          app.run(debug=True)
      EOF
      python app.py"