version: '3.8'

services:
  api:
    image: python:3.11-slim
    container_name: simple-api
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    command: |
      sh -c "
      pip install flask
      wget https://raw.githubusercontent.com/Sacon217/home-lab/docker/exercises/noname/simple-api/simple-api.py -O /mnt/simple-api/simple-api.py &&
      python -f /mnt/simple-api/simple-api.py
      "