version: '3.8'

services:
  simple-api:
    image: python:3.11-slim
    restart: always
    working_dir: /app
    environment:
      - PORT_NUMBER=${PORT_NUMBER}
    ports:
      - "0.0.0.0:${PORT_NUMBER}:${PORT_NUMBER}"
    command: |
      sh -c "
      apt-get update &&
      apt-get install -y wget &&
      pip install flask &&
      wget https://raw.githubusercontent.com/Sacon217/home-lab/refs/heads/main/docker/exercises/noname/simple-api/simple-api.py -O /app/simple-api.py &&
      python /app/simple-api.py
      "