version: '3.8'

services:
  api:
    image: python:3.11-slim
    container_name: simple-api
    restart: always
    working_dir: /app
    ports:
      - "5000:5000"
    command: |
      sh -c "
      apt-get update &&
      apt-get install -y wget &&
      pip install flask &&
      curl -o /app/simple-api.py https://raw.githubusercontent.com/Sacon217/home-lab/refs/heads/main/docker/exercises/noname/simple-api/simple-api.py &&
      python /app/simple-api.py
      "