version: '3'
services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    command:
      - "--config.file-/config/prometheus.yml"
    volumes:
      - prometheus_data:/prometheus
      - /etc/prometheus:/config/prometheus.yml
    ports:
      - 9090:9090
volumes:
  prometheus_data:
    driver: local