version: "3.9"

networks:
  private:
    driver: bridge
  edge:
    driver: bridge

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    networks: [private]
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "192.168.100.52:8080:80/tcp" # Change default ports for Pi-hole due to NPM using the 80 for HTTP
      - "192.168.100.52:8443:443/tcp" # Change default ports for Pi-hole due to NPM using the 443 for HTTPS
    expose:
      - "80"   # Expose to Docker network only (not host)
      - "443"  # Expose to Docker network only (not host)
   cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TZ: "America/Costa_Rica"
      FTLCONF_webserver_api_password: "${PIHOLE_PASSWORD}"
      FTLCONF_dns_listeningMode: "local"
    volumes:
      - "/srv/docker/pihole/etc-pihole:/etc/pihole"
      - "/srv/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    healthcheck:
      test: ["CMD-SHELL", "dig +short @127.0.0.1 pi.hole || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    depends_on: [pihole]
    networks: [edge, private]
    environment:
      TZ: "America/Costa_Rica"
    ports:
      - "80:80"
      - "443:443"
      - "192.168.100.52:81:81"
    volumes:
      - "/srv/docker/npm/data:/data"
      - "/srv/docker/npm/letsencrypt:/etc/letsencrypt"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
